---
# This playbook contains plays only for Controller

- name: Update & Upgrade
  become: true
  become_method: sudo
  script: "/home/{{ user_controller }}/{{ item }}"
  loop:
    - update.sh
    - maintance.sh
