---
# This playbook contains common plays that will be run on all nodes

- name: Run the update.sh and maintaince.sh scripts
  become: true
  become_method: sudo
  script: "/home/{{ user_default }}/{{ item }}"
  loop:
    - update.sh
    - maintance.sh

