---
# Main playbook

# It will work without this block of commands but it may be useful in the future
- name: CA machine tasks
  hosts: CA_machine
  remote_user: "{{ user_ca }}"

  roles:
    - ca

# Can I do it better?
# --------------------------------
- name: Controller tasks
  hosts: Controller
  connection: local

  roles:
    - controller

- name: Others tasks
  hosts: Others
  remote_user: "{{ user_default }}"

  roles: 
    - common
# --------------------------------
